#Apply to Cluster2
---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: eastwestgateway
#  namespace: istio-ingress
#spec:
#  selector:
#    istio: eastwestgateway
#  servers:
#    - port:
#        number: 15443
#        name: tls
#        protocol: TLS
#      tls:
#        mode: AUTO_PASSTHROUGH
#      hosts:
#        - "*"
#---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-echoserver
  namespace: curlserver
spec:
  host: eastwestgateway.istio-ingress.svc.cluster.local
  subsets:
  - name: echoserver
    labels:
      cluster: aks-cluster-one
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver-through-eastwest-gateway
  namespace: curlserver
spec:
  exportTo:
    - '.'
  hosts:
  - "echoserver.echoserver.global"
  gateways:
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: eastwestgateway.istio-ingress.svc.cluster.local
        subset: echoserver
        port:
          number: 15443
      weight: 100
