#Apply to Cluster2
---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: eastwestgateway
#  namespace: istio-ingress
#spec:
#  selector:
#    istio: eastwestgateway
#  servers:
#    - port:
#        number: 15443
#        name: tls
#        protocol: TLS
#      tls:
#        mode: AUTO_PASSTHROUGH
#      hosts:
#        - "*"
#---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-echoserver
  namespace: curlserver
spec:
  host: echoserver.echoserver.svc.cluster.local
  subsets:
  - name: echoserver-1
    labels:
      topology.istio.io/cluster: aks-cluster-one
  - name: echoserver-2
    labels:
      topology.istio.io/cluster: aks-cluster-two
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver-through-eastwest-gateway
  namespace: curlserver
spec:
  #exportTo:
  #  - '.'
  hosts:
  - "echoserver.echoserver.svc.cluster.local"
  http:
  - name: "cluster-1-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: "cluster-1"
    route:
    - destination:
        host: echoserver.echoserver.svc.cluster.local
        subset: echoserver-1
  - name: "cluster-2-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: "cluster-2"
    route:
    - destination:
        host: echoserver.echoserver.svc.cluster.local
        subset: echoserver-1