# https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#configuring-ingress-using-an-istio-gateway
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: echoserver-internal
  namespace: istio-ingress
spec:
  selector:
    istio: eastwestgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echoserver-internal
  namespace: echoserver
spec:
  hosts:
    - 'echoserver.echoserver.svc.cluster.local'
  gateways:
    - mesh
    - echoserver/echoserver-internal
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: echoserver.echoserver.svc.cluster.local
---