apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-echoserver-1
  namespace: istio-ingress
spec:
  selector:
    app: eastwestgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
